---
extends: default

ignore:
  - "node_modules/"
  - "docs/node_modules/"
  - ".docusaurus/"
  - "docs/.docusaurus/"
  - "docs/build/"
  - "target/"

rules:
  document-start: disable
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
