VERSION 0.8

LINT:
    FUNCTION

    ARG FIX="false"

    FROM node:alpine
    WORKDIR /holt

    # Install markdownlint
    RUN npm install -g markdownlint-cli

    # Copy the source code into the container
    COPY . .

    # Check the Markdown for linting errors
    IF [ "$FIX" == "true" ]
      RUN markdownlint --fix **/*.md || true
    ELSE
      RUN markdownlint **/*.md
    END

    # Save changes back to the local filesystem
    IF [ "$FIX" = "true" ]
        SAVE ARTIFACT ./* AS LOCAL .
    END
