VERSION 0.8

IMPORT github.com/earthly/lib/rust AS rust

CONTAINER:
    FUNCTION

    FROM rust:1.90.0-slim
    WORKDIR /holt

    # Initialize Rust
    DO rust+INIT --keep_fingerprints=true

FORMAT:
    FUNCTION

    ARG FIX="false"

    DO +CONTAINER

    # Install leptosfmt
    DO rust+CARGO --args="install leptosfmt"

    COPY . .

    IF [ "$FIX" = "true" ]
        RUN leptosfmt "crates/**/*.rs"
    ELSE
        RUN leptosfmt --check "crates/**/*.rs"
    END

    # Save changes back to the local filesystem
    IF [ "$FIX" = "true" ]
        SAVE ARTIFACT ./* AS LOCAL .
    END
