set shell := ["flox", "activate", "--", "sh", "-cu"]

[private]
default:
    @just --list --list-submodules

# Serve the Holt Book for our UI components
serve:
    trunk serve

# Run visual regression tests
test-visual:
    cargo run --bin visual-regression --features visual-regression
