[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
create_nonce = false

[watch]
watch = []
ignore = ["tests/"]

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false

[tools]
tailwindcss = "4.1.4"
