---
name: Continuous Integration

"on":
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  targets:
    name: Enumerate Just recipes
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.export-targets.outputs.targets }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false

      - name: Install Just
        uses: taiki-e/install-action@e43a5023a747770bfcb71ae048541a681714b951 # 2.62.33
        with:
          tool: just

      - name: Export targets
        id: export-targets
        run: echo "targets=$(just --list | awk '/build-|check-|format-|lint-|test-/{print $1}' | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  checks:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: targets

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.targets.outputs.matrix) }}

    services:
      postgres:
        image: postgres@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: otterdone
          POSTGRES_PASSWORD: otterdone
          POSTGRES_DB: otterdone
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false

      - name: Install Flox
        uses: flox/install-flox-action@ba0eb4eb776f1d3b47279d7980f6643caffd8c41 # 2.0.0
        with:
          version: 1.6.1

      - name: Remove Flox installer (if it exists)
        run: rm -f flox.x86_64-linux.deb

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # 2.8.1
        with:
          prefix-key: "v0-${{ matrix.target }}"

      - name: Run check with Just
        uses: flox/activate-action@bdcbcf8d84af6f503e588ae4125e48133787df95 # 1.0.0
        with:
          command: just ${{ matrix.target }}

  success:
    name: All checks succeeded
    runs-on: ubuntu-latest

    permissions: {}

    needs: checks
    if: always()

    steps:
      - name: Check if all checks succeeded
        # `needs` is a list of job names, which themselves are generated from
        # the output of `just --list`, so we ignore the template injection here.
        # zizmor: ignore[template-injection]
        run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
